### ISSUE TITLE
Yeelight Support

### ISSUE THREAD

**Issue by StephanBruh** [koningcool/F1MV-Govee-Tradfri-LightBridge#1]
I really like the idea, would be cool if support for yeelight is possible!

**Comment by JustJoostNL** [comment]
I will have a look into it!

**Comment by JustJoostNL** [comment]
@StephanBruh I am currently working on it! It will be a separate lightweight JavaScript application. I think it will be done before the start of the race!

**Comment by StephanBruh** [comment]
Great news! Can't wait to try it out, thanks a lot

Op zo 23 okt. 2022 14:59 schreef koningcool ***@***.***>:

**Comment by JustJoostNL** [comment]
Are you using windows, macos or linux?

**Comment by StephanBruh** [comment]
@koningcool I'm on Windows

**Comment by JustJoostNL** [comment]
Will have a build soon, I can't test it because I dont have the lights, so lets hope it works!

**Comment by StephanBruh** [comment]
Nice, if you want to test something let me know

**Comment by JustJoostNL** [comment]
For sure!

**Comment by JustJoostNL** [comment]
@StephanBruh Check your discord DM!😁

**Comment by JustJoostNL** [comment]
Support added in a separate lightweight JavaScript program
https://github.com/koningcool/F1MV-YeeLight
